// Generated by gencpp from file dobot/TransPuzzleCmd.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_TRANSPUZZLECMD_H
#define DOBOT_MESSAGE_TRANSPUZZLECMD_H

#include <ros/service_traits.h>


#include <dobot/TransPuzzleCmdRequest.h>
#include <dobot/TransPuzzleCmdResponse.h>


namespace dobot
{

struct TransPuzzleCmd
{

typedef TransPuzzleCmdRequest Request;
typedef TransPuzzleCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TransPuzzleCmd
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::TransPuzzleCmd > {
  static const char* value()
  {
    return "80257a33fbe8eda7e69a8ee2a7a08d79";
  }

  static const char* value(const ::dobot::TransPuzzleCmd&) { return value(); }
};

template<>
struct DataType< ::dobot::TransPuzzleCmd > {
  static const char* value()
  {
    return "dobot/TransPuzzleCmd";
  }

  static const char* value(const ::dobot::TransPuzzleCmd&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::TransPuzzleCmdRequest> should match 
// service_traits::MD5Sum< ::dobot::TransPuzzleCmd > 
template<>
struct MD5Sum< ::dobot::TransPuzzleCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::TransPuzzleCmd >::value();
  }
  static const char* value(const ::dobot::TransPuzzleCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::TransPuzzleCmdRequest> should match 
// service_traits::DataType< ::dobot::TransPuzzleCmd > 
template<>
struct DataType< ::dobot::TransPuzzleCmdRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::TransPuzzleCmd >::value();
  }
  static const char* value(const ::dobot::TransPuzzleCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::TransPuzzleCmdResponse> should match 
// service_traits::MD5Sum< ::dobot::TransPuzzleCmd > 
template<>
struct MD5Sum< ::dobot::TransPuzzleCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::TransPuzzleCmd >::value();
  }
  static const char* value(const ::dobot::TransPuzzleCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::TransPuzzleCmdResponse> should match 
// service_traits::DataType< ::dobot::TransPuzzleCmd > 
template<>
struct DataType< ::dobot::TransPuzzleCmdResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::TransPuzzleCmd >::value();
  }
  static const char* value(const ::dobot::TransPuzzleCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_TRANSPUZZLECMD_H
